//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::eligible_cases::Entity as EligibleCases;
pub use super::insurer::Entity as Insurer;
pub use super::iro::Entity as Iro;
pub use super::patient::Entity as Patient;
pub use super::provider::Entity as Provider;
