//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "provider")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub provider_id: i32,
    pub provider_name: String,
    pub provider_address_1: Option<String>,
    pub provider_address_2: Option<String>,
    pub provider_zip: Option<String>,
    pub provider_contact_f_name: Option<String>,
    pub provider_contact_l_name: Option<String>,
    pub provider_phone: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::eligible_case::Entity")]
    EligibleCase,
}

impl Related<super::eligible_case::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EligibleCase.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
